version: "3.0"

services:
    front:
        build:
            context: .
            dockerfile: Dockerfile.front
        ports:
            - 8080:8080
        depends_on:
            - back
        image: gcr.io/pixie-prod/demos/px-mongo/frontend:0.1.0

    back:
        build:
            context: .
            dockerfile: Dockerfile.back
        ports:
            - 8085:8085
        depends_on:
            - mongodb
        image: back:latest
        
    load:
        build:
            context: .
            dockerfile: Dockerfile.load
        depends_on:
            - back
        image: load:latest

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017