apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: back
    spec:
      containers:
      - env:
        - name: CONN_STR
          value: mongodb://mongodb:27017
        - name: PORT
          value: "8085"
        image: gcr.io/pixie-prod/demos/px-mongo/backend:1.0.0
        imagePullPolicy: ""
        name: back
        ports:
        - containerPort: 8085
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
