apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: load
  name: load
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: load
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: load
    spec:
      containers:
      - image: gcr.io/pixie-prod/demos/px-mongo/load:0.1.0
        imagePullPolicy: ""
        name: load
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
